version: 2.1
jobs:
  build:
    docker:
      # Specify the same version as your local development environment
      - image: circleci/node:10.20.1

    steps:
      - checkout
      - run: npm install
      - run: npm test
